name: "Build with Meson"

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cross-file: [musl-static, mingw-w64, djgpp-gcc]
        include:
          # Linux x86_64
          - cross-file: musl-static
            file: x86_64
          # Windows x86_64
          - cross-file: mingw-w64
            file: x86_64.exe
          # Windows i386
          - cross-file: djgpp-gcc
            file: i386.exe
            extra-step: "sed -i '/^ LINK_ARGS/d' build.ninja"


    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure dependencies
      run: |
       sudo apt install meson ninja-build musl-tools gcc-mingw-w64
       cd /opt
       wget https://github.com/andrewwutw/build-djgpp/releases/download/v3.1/djgpp-linux64-gcc1020.tar.bz2
       tar -xf djgpp-linux64-gcc1020.tar.bz2
 
    - name: Configure toolchain
      run: |
       mkdir build
       cd build
       meson --cross-file ../cross-files/${{ matrix.cross-file }}.txt ..
       ${{ matrix.extra-step }}

    - name: Build project
      run: |
       cd build
       ninja

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: memorylatency-${{ matrix.file }}
        path: build/src/memorylatency-${{ matrix.file }}
 
